//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTİTYPROJEUYGULAMA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MÜŞTERİ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_MÜŞTERİ()
        {
            this.TBL_SATIŞ = new HashSet<TBL_SATIŞ>();
        }
    
        public int MÜŞTERİID { get; set; }
        public string MÜŞTERİAD { get; set; }
        public string MÜŞTERİSOYAD { get; set; }
        public string ŞEHİR { get; set; }
        public Nullable<bool> DURUM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_SATIŞ> TBL_SATIŞ { get; set; }
    }
}
