//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTİTYPROJEUYGULAMA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SATIŞ
    {
        public int SATIŞID { get; set; }
        public Nullable<int> ÜRÜN { get; set; }
        public Nullable<int> MÜŞTERİ { get; set; }
        public Nullable<decimal> FİYAT { get; set; }
        public Nullable<System.DateTime> TARİH { get; set; }
    
        public virtual TBL_MÜŞTERİ TBL_MÜŞTERİ { get; set; }
        public virtual TBL_ÜRÜN TBL_ÜRÜN { get; set; }
    }
}
